name: tidymodels-dvc-mashup
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: r-lib/actions/setup-r@master
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          apt-get update -y 
          apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev
          dvc get-url https://gist.github.com/slopp/aaa98f5c9d8d5161396b6afedb1b1b52#file-housing-csv housing.csv
          dvc repro
          
          cat fit_model.html >> report.md 
          cml-send-comment report.md